### ISSUE TITLE
Check for document.readyState === "interactive"

### ISSUE THREAD

**Issue by Tbstr** [requirejs/domReady#18]
Hey there,

is there a reason for the initial check in line 91 is only for 'complete', not also for  'interactive'.  Since 'interactive' marks the state of having sent the DOMContentLoaded event it seems appropriate to me.

In my setup domReady seems to initialize shortly after the DOMContentLoaded event has fired and therefore waits all the way till the window.load event fires. Because of some big images on the site this means a lot of time.

Thanks for your opinion
Tobi

**Comment by Tbstr** [comment]
Just found issue #1, sorry for that. But a check for IE9 seems like a better solution than the long delay.

Best
Tobi

**Comment by jrburke** [comment]
The issue was reported for IE9, but I am not aware if it was actually fixed in later IE browsers. And traditionally user agent checks usually fail at some point given that there are some IE embedding cases that change the user agent.

I appreciate wanting the faster firing, but in this case I prefer to have a reliable if slower check than fielding issues around it firing incorrectly in some edge cases.

I encourage you just to keep a fork of the code and modify it to the browsers you know you only have to worry about. This code has not really changed in quite a while. I do not expect to do major rewrites of it, so keeping a fork is not likely to suffer from code drift.

**Comment by Tbstr** [comment]
Alright, thanks.
