### ISSUE TITLE
Update isBrowser?

### ISSUE THREAD

**Issue by necolas** [requirejs/domReady#6]
In require.js you use:

``` js
isBrowser = !!(typeof window !== 'undefined' && navigator && document)
```

This may be an intentional difference, but I didn't manage to track down a reason for it.

Thanks

**Comment by e-maximus** [comment]
I have an issue with detection of MSIE browser when DOMContentLoaded is missed, because indexOf("MSIE ") returns -1 when MSIE is not found and condition !window.navigator.userAgent.indexOf("MSIE ") is not pass. Is this a bug?
```javascript
(document.readyState === "interactive" && !window.navigator.userAgent.indexOf("MSIE ")
```

My userAgent is 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

Thanks
